name: Main CI workflow
on: [push, pull_request]
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags')
    needs: test
    uses: "emaaforlin/JasferInventoryServer/.github/workflows/test.yml"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
